### PR TITLE
Adding bower.json for Bower support

### PR DESCRIPTION
**Pull request by arvidbjorkstrom**
Added a bower.json to enable Bower support

### CODE REVIEW

**Comment by arvidbjorkstrom** [comment]
`bower register foundation-select git://github.com/roymckenzie/foundation-select`
when merged

**Comment by arvidbjorkstrom** [comment]
Has @roymckenzie given up on this plugin? :)

**Comment by roymckenzie** [comment]
Thanks for pining me. Sorry for the delay. I need to go in and rewrite this plugin, but that is a separate issue outside of this pull request and I thank you for your contribution! 🙇

**Comment by arvidbjorkstrom** [comment]
I've got a few fixes coming up for this. I'll just clean up my code a bit before adding another pull request. :)

**Comment by roymckenzie** [comment]
Rad! Thank you! +1

**Pull request merged**
